application: flask-social-blueprint
version: 3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: '3650d'

env_variables:
  TMP: C:\Users\WOOYEK\AppData\Local\Temp

libraries:
- name: ssl
  version: latest

handlers:

- url: /.*
  script: main.app
